development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: autosuggest_and_tagging_development
  pool: 5
  username: root
  password: studior
  socket: /var/run/mysqld/mysqld.sock

